services: 
  awsflask: 
    container_name: awsflask
    build: . 
    restart: always
    expose: 8000
    # ports: 
    #   - 8000:8000 
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - default
      - proxy 
      
  mysql: 
    container_name: mysql
    image: mysql
    restart: always 
    env_file:
      - .env
    # ports: 
    #   - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 5s
      timeout: 30s
      retries: 2
      start_period: 0s

networks: 
  default: 
  proxy: 
    name: proxy 
    external: true 