services: 
  awsflask: 
    container_name: awsflask
    image: ghcr.io/meyersa/awsflask
    restart: always
    expose: 
      - 8000
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASS=${MYSQL_PASS}
      - MYSQL_DB=${MYSQL_DB}

networks: 
  default: 
    name: proxy 
    external: true