services: 
  awsflask: 
    container_name: awsflask
    build: . 
    restart: always
    expose: 
      - 8000
    env_file:
      - .env
    networks:
      - default
      - proxy 
      
networks: 
  default: 
  proxy: 
    name: proxy 
    external: true 